In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [65]:
y = df['math score']
x = df.drop(['math score'] , axis = 'columns')

In [68]:
num_feature = x.select_dtypes(exclude = "object").columns
cat_feature = x.select_dtypes(include = "object").columns

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer

num_t = StandardScaler()
cat_t = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("oneHotEncoder" , cat_t , cat_feature),
        ("StandardScaler" , num_t , num_feature)
    ]
)

In [71]:
x = preprocessor.fit_transform(x)

In [72]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y , train_size = 0.2 , random_state = 10)

In [77]:
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.neighbors import KNeighborsRegressor

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor

from sklearn.svm import SVR

from sklearn.linear_model import LinearRegression, Ridge,Lasso

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

from sklearn.model_selection import RandomizedSearchCV

In [78]:
def evaluated(true , predict):
    mae = mean_absolute_error(true, predict)
    mse  = mean_squared_error(true , predict)
    rmse = np.sqrt(mean_squared_error(true, predict))
    r2_square = r2_score(true , predict)
    return mae , mse , r2_square

In [79]:
models = {

    "Linear Regression": LinearRegression(),

    "Lasso": Lasso(),

    "Ridge": Ridge(),

    "K-Neighbors Regressor": KNeighborsRegressor(),

    "Decision Tree": DecisionTreeRegressor(),

    "Random Forest Regressor": RandomForestRegressor(),

    "AdaBoost Regressor": AdaBoostRegressor()

}

In [82]:
model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    model_train_mae , model_train_rmse, model_train_r2 = evaluated(y_train, y_train_pred)
    model_test_mae , model_test_rmse, model_test_r2 = evaluated(y_test, y_test_pred)
    print(list(models.keys())[i])

    model_list.append(list(models.keys())[i])
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))
    print('----------------------------------')
    print('Model performance for Test set')

    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))

    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))

    print("- R2 Score: {:.4f}".format(model_test_r2))

    r2_list.append(model_test_r2)

    

    print('='*35)

    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 25.2792
- Mean Absolute Error: 3.9357
- R2 Score: 0.8770
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 30.4802
- Mean Absolute Error: 4.4025
- R2 Score: 0.8707
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 39.6723
- Mean Absolute Error: 4.8918
- R2 Score: 0.8069
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 45.4225
- Mean Absolute Error: 5.3580
- R2 Score: 0.8073
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 25.3115
- Mean Absolute Error: 3.9398
- R2 Score: 0.8768
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 30.5507
- Mean Absolute Error: 4.3993
- R2 Score: 0.8704
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 34.4230
- Mean Absolute Error: 4.5910
- R2 Score: 0.8325
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 61.7046
- Mean Absolute Error: 6.2340
- R2 Score: 0.7382
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 84.8962
- Mean Absolute Error: 7.3262
- R2 Score: 0.6398
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 5.2038
- Mean Absolute Error: 1.8356
- R2 Score: 0.9747
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 47.3255
- Mean Absolute Error: 5.5397
- R2 Score: 0.7992
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 27.7344
- Mean Absolute Error: 4.4222
- R2 Score: 0.8650
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 50.9868
- Mean Absolute Error: 5.5823
- R2 Score: 0.7837
===================================